const bypassToken = 'vOINkES15fLSseVSSERuvOINkES15fLSseVSSERuvOINkES15fLSseVSSERuvOINkES15fLSseVSSERuvOINkES15fLSseVSSERu';

export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 100,

		// Random token that can be provided in the URL to bypass the cached version of the asset, by requesting the asset
		// with a __prerender_bypass=<token> cookie.
		//
		// Making a `GET` or `HEAD` request with `x-prerender-revalidate: <token>` will force the asset to be re-validated.
		bypassToken,
		allowQuery: ['rev']
	}
};

/**
 * @type {{name: {first: string, last: string}}}
 */
export async function load(ev) {
	const res = await fetch('https://randomuser.me/api');
	const data = await res.json();
	console.log(ev.url.searchParams.get('rev'));
	return data.results[0];
}

